### ISSUE TITLE
Where is motion detect?

### ISSUE THREAD

**Issue by itProfi** [Jey-Cee/iobroker.onvif-alt#7]
Hello! Where is motion detect future? Is it planned?
![Скриншот 04-01-2020 133025](https://user-images.githubusercontent.com/6728198/71764929-61c41500-2eff-11ea-8870-754f36ab4a12.jpg)
![Скриншот 04-01-2020 143506](https://user-images.githubusercontent.com/6728198/71764943-743e4e80-2eff-11ea-92a4-d4ac58ac8450.jpg)

**Comment by Jey-Cee** [comment]
I am planning to integrate this feature. But it looks like i have to extend the extend the onvif-nvt modul, so it takes a while.

**Comment by itProfi** [comment]
ok, thanks!
